version: "3.4"

services:
  webserver:
    build:
      dockerfile: ./.docker/bin/php74/Dockerfile
      context: ./
      network: host
    container_name: "${DOCKER_NAME_PREFIX}_webserver"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT-80}:80"
